# Generated by Django 5.1.15 on 2026-09-04 13:54

import catalog.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название (ZH)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Эмодзи для карточек и карты",
                        max_length=8,
                        verbose_name="Значок",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2e7d32",
                        help_text="HEX, например #2e7d32",
                        max_length=7,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=100, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["order", "name"],
            },
            bases=(catalog.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Код"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "title_zh",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название (ZH)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Описание (EN)"),
                ),
                (
                    "description_zh",
                    models.TextField(blank=True, verbose_name="Описание (ZH)"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Длительность"
                    ),
                ),
                (
                    "duration_en",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Длительность (EN)"
                    ),
                ),
                (
                    "duration_zh",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Длительность (ZH)"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("all_year", "Круглый год"),
                            ("summer", "Лето"),
                            ("winter", "Зима"),
                            ("spring_autumn", "Весна и осень"),
                        ],
                        default="all_year",
                        max_length=20,
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Лёгкий"),
                            ("medium", "Средний"),
                            ("hard", "Сложный"),
                        ],
                        default="easy",
                        max_length=20,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="routes/", verbose_name="Обложка"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
            ],
            options={
                "verbose_name": "Маршрут",
                "verbose_name_plural": "Маршруты",
                "ordering": ["title"],
            },
            bases=(catalog.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название (ZH)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Описание (EN)"),
                ),
                (
                    "description_zh",
                    models.TextField(blank=True, verbose_name="Описание (ZH)"),
                ),
                ("lat", models.FloatField(verbose_name="Широта")),
                ("lng", models.FloatField(verbose_name="Долгота")),
            ],
            options={
                "verbose_name": "Село",
                "verbose_name_plural": "Сёла округа",
                "ordering": ["name"],
            },
            bases=(catalog.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Код"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "title_zh",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название (ZH)"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="Краткое описание"),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Краткое описание (EN)"
                    ),
                ),
                (
                    "short_description_zh",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Краткое описание (ZH)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Описание (EN)"),
                ),
                (
                    "description_zh",
                    models.TextField(blank=True, verbose_name="Описание (ZH)"),
                ),
                (
                    "fact_note",
                    models.TextField(
                        blank=True,
                        help_text="Оговорки о статусе объекта, ограничениях доступа, условности данных",
                        verbose_name="Примечание о достоверности",
                    ),
                ),
                ("lat", models.FloatField(verbose_name="Широта")),
                ("lng", models.FloatField(verbose_name="Долгота")),
                (
                    "address",
                    models.CharField(blank=True, max_length=250, verbose_name="Адрес"),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("all_year", "Круглый год"),
                            ("summer", "Лето"),
                            ("winter", "Зима"),
                            ("spring_autumn", "Весна и осень"),
                        ],
                        default="all_year",
                        max_length=20,
                        verbose_name="Сезонность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Действующий"),
                            ("construction", "Строится"),
                            ("planned", "Планируется"),
                            ("closed", "Не действует"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус объекта",
                    ),
                ),
                (
                    "in_district",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите отметку для объектов регионального контекста",
                        verbose_name="В границах округа",
                    ),
                ),
                (
                    "is_fictional",
                    models.BooleanField(
                        default=False,
                        help_text="Название и услуги придуманы для учебной демонстрации",
                        verbose_name="Условные данные",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Через запятую",
                        max_length=250,
                        verbose_name="Теги",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attractions",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто — если объект находится за пределами округа",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attractions",
                        to="catalog.village",
                        verbose_name="Село",
                    ),
                ),
            ],
            options={
                "verbose_name": "Туристический объект",
                "verbose_name_plural": "Туристические объекты",
                "ordering": ["title"],
            },
            bases=(catalog.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="attractions/", verbose_name="Изображение"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись"
                    ),
                ),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="Обложка"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=100, verbose_name="Порядок"),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.attraction",
                        verbose_name="Объект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
                "ordering": ["-is_cover", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Код"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название (EN)"
                    ),
                ),
                (
                    "title_zh",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название (ZH)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Описание (EN)"),
                ),
                (
                    "description_zh",
                    models.TextField(blank=True, verbose_name="Описание (ZH)"),
                ),
                (
                    "fact_note",
                    models.TextField(
                        blank=True, verbose_name="Примечание о достоверности"
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Дата начала")),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="catalog.attraction",
                        verbose_name="Площадка",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="catalog.village",
                        verbose_name="Село",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "ordering": ["date_start"],
            },
            bases=(catalog.models.TranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="catalog.attraction",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "attraction"),
                        name="unique_user_attraction_favorite",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                            (5, "★★★★★"),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создан"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Одобрен"),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.attraction",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "attraction"),
                        name="unique_user_attraction_review",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Комментарий"
                    ),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_points",
                        to="catalog.attraction",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="catalog.route",
                        verbose_name="Маршрут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка маршрута",
                "verbose_name_plural": "Точки маршрута",
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("route", "attraction"), name="unique_route_attraction"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="attraction",
            index=models.Index(
                fields=["is_published", "category"],
                name="catalog_att_is_publ_f17050_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attraction",
            index=models.Index(
                fields=["is_published", "village"],
                name="catalog_att_is_publ_381028_idx",
            ),
        ),
    ]
